CREATE USER wirewizard WITH PASSWORD 'ww';

CREATE DATABASE keys;

GRANT CONNECT ON DATABASE keys TO wirewizard;
GRANT ALL PRIVILEGES ON DATABASE keys TO wirewizard;
REVOKE ALL PRIVILEGES ON DATABASE keys FROM postgres;

\c keys wirewizard;

CREATE SCHEMA IF NOT EXISTS wireguard;

GRANT USAGE ON SCHEMA wireguard TO wirewizard;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA wireguard TO wirewizard;
REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA wireguard FROM postgres;